service: wolfonair-back

provider:
  name: aws
  runtime: nodejs10.x
  region: ap-northeast-2
  state: dev

plugins:
  - serverless-webpack
  - serverless-offline

functions:
  api:
    handler: src/server.handler
    events:
      - http:
          path: /
          method: ANY
      - http:
          path: /{any*} # 아무 패스나 들어올 수 있도록
          method: ANY
